## 服务配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://huangjingze.cn:3306/online_exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: huang
    driver-class-name: com.mysql.jdbc.Driver

## mybatis配置
mybatis:
  typeAliasesPackage: com.example.demo.dto
  mapperLocations: classpath*:mapping/*.xml






